### ISSUE TITLE
New Lines in Match with --replacement-js-dynamic

### ISSUE THREAD

**Issue by danielcrabtree** [mathiasrw/rexreplace#3]
rexreplace crashes if the regex match includes new line characters when using `--replacement-js-dynamic`.

This seems to be because it generates invalid code when the match contains new line characters. The issue seems to be line 137 in core.js as new lines cannot be used in standard javascript strings.

**Comment by mathiasrw** [comment]
Thank you so much for your bug report. 

Im on the case.

**Comment by mathiasrw** [comment]
Hi @danielcrabtree 

> rexreplace crashes if the regex match includes new line characters when using `--replacement-js-dynamic`.

I am not able to replicate the error. 

Is it the `\n` you are referring to? Did you enclose the first parameter in `'` og `"` ? Could it be a console-does-strange-things-with-my-command issue? If you have an example of a command that triggers the error that would be much appreciated.

**Comment by danielcrabtree** [comment]
With this file as input:
```
Hello World
Hello World
Hello World
```

With this command:
`rexreplace "Hello World" "\"Hi\"" wwwroot/scripts/test.txt --replacement-js-dynamic --output`

It outputs:
```
Hi
Hi
Hi
```

With this command:
`rexreplace "World((.|[\r\n])*)Hello" "\"$1\"" wwwroot/scripts/test.txt --replacement-js-dynamic --output`

It outputs:
```
undefined:1
var $0="World
       ^^^^^^
SyntaxError: Invalid or unexpected token
    at node_modules\rexreplace\build\ES6\rexreplace.cli.bundle.js:15573:42
    at RegExp.[Symbol.replace] (native)
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
    at node_modules\rexreplace\build\ES6\rexreplace.cli.bundle.js:15486:24
    at tryToString (fs.js:457:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:444:12)
```

**Comment by danielcrabtree** [comment]
It might be worth noting that this command:
`rexreplace "World((.|[\r\n])*)Hello" "\"Hi\"" wwwroot/scripts/test.txt --replacement-js-dynamic --output`

Works fine and outputs:
`﻿Hello Hi World`

So the issue requires both new line characters in the pattern to match and references in the replacement. The issue seems to be in how it writes out the references into variables for dynamic execution.

**Comment by mathiasrw** [comment]
You are awesome! Ill dig further...

**Comment by mathiasrw** [comment]
version 2.5.3 up on npm - please verify that this fixes you issue

**Comment by danielcrabtree** [comment]
I've tested and the issue is fixed now. 

@mathiasrw thanks for getting it fixed so quickly.

**Comment by mathiasrw** [comment]
Awesome - and thank you for a very well described problem. Makes about 80% of fixing something... :)
